TYPE_MAP = {
    'utf8': 'str',
    'filename': 'str',
    'gunichar': 'str',
    'char': 'str',
    'gboolean': 'bool',
    'none': None,
    'double': 'float',
    'float': 'float',
    'int': 'int',
    'guint': 'int',
    'guint8': 'int',
    'guint16': 'int',
    'guint32': 'int',
    'guint64': 'int',
    'gint8': 'int',
    'gint16': 'int',
    'gint32': 'int',
    'gint64': 'int',
    'gsize': 'int',
    'gssize': 'int',
    'long': 'int',
    'GLib.DateDay': 'int',
    'GLib.DateYear': 'int',
    'GLib.TimeSpan': 'int',
    'gpointer': 'object'
}
